### ISSUE TITLE
2. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar

### ISSUE THREAD

**Issue by fullybaked** [the-collab-lab/tcl-54-smart-shopping-list#2]
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouterdotcom.fly.dev/docs/en/v6/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

**Comment by mtfoley** [comment]
Y'all can try this link for the `NavLink` component docs. Looks like the link in the issue description isn't working.

https://reactrouter.com/en/main/components/nav-link
cc @fullybaked
