### ISSUE TITLE
4. As a user, I want to add a new item to my shopping list so I can start recording purchases

### ISSUE THREAD

**Issue by fullybaked** [the-collab-lab/tcl-54-smart-shopping-list#4]
## Summary
Users need to be able to add items to their shopping lists. To do this, the `AddItem` view should present them with a form that allows them to enter two things:
1. The name of the item, and
2. An estimate of when they think they’ll need to buy the item again.

[The README file for the shopping list API](https://github.com/the-collab-lab/smart-shopping-list-next/blob/main/src/api/README.md) will be helpful as you work on this feature.

## Acceptance criteria
UI-related tasks:
- [x] The `Add Item` view displays a form that allows them to enter the name of the item and select how soon they anticipate needing to buy it again. There should be 3 choices for this:
	- “Soon”, corresponding to 7 days
	- “Kind of soon”, corresponding to 14 days
	- “Not soon”, corresponding to 30 days
- [x] The input that accepts the name of the item has a semantic `label` element associated with it
- [x] The user can submit this form with both the mouse and the `Enter` key  
- [x] When the user submits the form, they see a message indicating that the item either was or was not saved to the database.

Data-related tasks:
- [x] The `console.log` in the `addItem` function in `src/api/firebase.js`  is replaced with a function that adds the new document to the Firestore database. That function will be imported from the `firebase/firestore` module.
- [x]  The user’s soon/not soon/kind of soon choice is used to calculate `nextPurchasedDate`

## Notes
- When this feature is implemented correctly, new items will *automatically* show up in the list view because `streamListItem` gets new data from Firestore every time there’s a change.
- You will know your `<label>` is correctly implemented if you click on the label and keyboard focus moves to the related input. Refer to [the MDN docs on `<label>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) for more info.
- Users will be able to submit the form with the `Enter` key if you listen for the right JavaScript event on the right element! If you're adding an `onKeyDown` listener anywhere, you might be overcomplicating things.
- The add item form has the potential to be a lot of scope. [The wireframe for the "add item" page](https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/add-item.png) has several notes related to accessibility and UX.

**Comment by daredtech** [comment]
Consider how your message is displayed on different browsers:

(Chrome):
<img width="901" alt="Screen Shot 2023-01-20 at 12 56 12 PM" src="https://user-images.githubusercontent.com/44907238/213803881-df032c65-baf5-456d-b863-506b7a55bced.png">

(Safari):
<img width="915" alt="Screen Shot 2023-01-20 at 12 56 42 PM" src="https://user-images.githubusercontent.com/44907238/213803933-a99ea89a-ae65-4fd0-b82f-f5b4674aa8f8.png">

Is there a way to make it more user-friendly?
