### ISSUE TITLE
Issue 23. SVG Import Debug

### ISSUE THREAD

**Issue by alex-andria** [the-collab-lab/tcl-54-smart-shopping-list#46]
## Summary
Debug SVGs so that is displays in development and not just https://localhost:3000.

## Criteria

- [x] Solve the issue on how to import SVGs in React and Vite

**Comment by mtfoley** [comment]
@alex-andria i noticed one other thing in our app. This line (import from .png with absolute path) seems to be working in production: https://github.com/the-collab-lab/tcl-54-smart-shopping-list/blob/main/src/views/Home.jsx#L7

**Comment by mtfoley** [comment]
Also this reference might be helpful (if a little abstract): https://www.freecodecamp.org/news/how-to-import-svgs-in-react-and-vite/amp/

**Comment by alex-andria** [comment]
Thanks for bringing this issue up @mtfoley! To be able to import ReactComponent SVGs I had to replace `svgr({ exportAsDefault: true })` with `svgr()` in `vite.config.js`. Then I was able to follow the steps here: https://www.freecodecamp.org/news/how-to-import-svgs-in-react-and-vite/amp/ to use SVGs as React components
